# Completion scripts for the jig binary

completion_bash() {
    _description "Generate bash completion script for the jig binary"
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
# Generated by: jig completion bash
# Add to ~/.bashrc: source <(jig completion bash)

_jig_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    local typed=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")
    local prefix=""
    for word in "${typed[@]}"; do
        [[ "$word" == -* ]] && break
        prefix="${prefix:+${prefix}_}${word}"
    done

    COMPREPLY=($(compgen -W "$(jig __complete "$prefix" "$prev" "$cur" 2>/dev/null)" -- "$cur"))
}

complete -F _jig_complete jig
COMPLETION
}

completion_zsh() {
    _description "Generate zsh completion script for the jig binary"
    _param_parse "$@" || return 1
    cat << 'COMPLETION'
# Generated by: jig completion zsh
# Add to ~/.zshrc: source <(jig completion zsh)

_jig() {
    local cur="${words[CURRENT]}"
    local prev="${words[CURRENT-1]}"

    local -a cmd_words=()
    local word
    local n=$(( CURRENT > 2 ? CURRENT - 2 : 0 ))
    for word in "${words[@]:1:$n}"; do
        [[ "$word" == --* ]] && break
        cmd_words+=("$word")
    done
    local prefix="${(j:_:)cmd_words}"

    local -a results
    results=($(jig __complete "$prefix" "$prev" "$cur" 2>/dev/null))
    compadd -- "${results[@]}"
}

compdef _jig jig
COMPLETION
}

_complete_params "completion_bash"
_complete_params "completion_zsh"
